"use client";
import Sidebar from '../components/sidebar';
import './globals.css';
import { Inter } from 'next/font/google';
import Image from 'next/image';
import { usePathname } from 'next/navigation';
import Upgrade from '../../public/images/UpgradeImage.png';

const inter = Inter({ subsets: ['latin'] });



export default function RootLayout({ children }) {
  const pathname = usePathname();
  return (
    <html lang="en">
      <head>
      <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body className={inter.className}>
        <div className="flex h-screen">
          <Sidebar />
          <div className="flex-1 px-8 py-2 bg-white">
          <div className="flex justify-between items-center mb-4">
            {pathname ==='/'?
            <h1 className="text-[24px] font-[500] text-[#101010]">My Posts</h1>
            :pathname === '/post-generator'?
            <div className='flex flex-col'>
              <h1 className="text-[24px] font-[500] text-[#101010]">Generate post with AI</h1>
              <p className='text-gray-500 text-[12px] '>Select a template to generate high quality posts using AI</p>
            </div>
             :pathname === '/post-generator/post-from-scratch'?
            <div className='flex flex-col'>
              <h1 className="text-[24px] font-[500] text-[#101010]">Generate a post From Scratch</h1>
              <p className='text-gray-500 text-[12px] '>You got an idea? we could generate a post from it.</p>
            </div>
            :''


          }
        <Image src={Upgrade} width={390} height={40} alt="upgrade" />
         </div>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
